services:
  jellyfin:
    image: jellyfin/jellyfin
    volumes:
      - ./jellyfin/data:/data
      - ./jellyfin/config:/config # seperate data and config
      - ./jellyfin/cache:/cache
      - ./jellyfin/log:/log
      - ./jellyfin/fallbackfonts:/fallbackfonts # fix chinese subtitle
      - ./jellyfin/media:/media
    ports:
      - 27964:27964
    user: ${UGID:?err}
    userns_mode: keep-id # currently not implemented by podman-compose, use `PODMAN_USERNS=keep-id podman-compose up`
    entrypoint: ["/jellyfin/jellyfin", "-d", "/data", "-C", "/cache", "-c", "/config", "-l", "/log", "--ffmpeg", "/usr/lib/jellyfin-ffmpeg/ffmpeg"]
    #restart: no
  sonarr:
    image: linuxserver/sonarr
    ports:
      - 3921:8989
    volumes:
      - ./sonarr/config:/config
      - ./sonarr:/data
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    ports:
      - 3920:9117
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    restart: unless-stopped
  qbittorrent:
    image: linuxserver/qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - ./qbittorrent/downloads:/downloads
    ports:
      - 3910:8080
      - 39881:6881
      - 39881:6881/udp
    restart: unless-stopped
  flaresolverr:
    image: flaresolverr/flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Asia/Shanghai
    ports:
      - 3919:8191
    restart: unless-stopped

