version: '3'
services:
  jellyfin:
    image: linuxserver/jellyfin:10.8
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/media:/media
    ports:
      - 3900:8096
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr:3
    ports:
      - 3921:8989
    volumes:
      - ./sonarr/config:/config
      - ./sonarr:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett:0.20
    ports:
      - 3920:9117
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    restart: unless-stopped
  qbittorrent:
    image: linuxserver/qbittorrent:4.5
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - ./qbittorrent/downloads:/downloads
    ports:
      - 3910:8080
      - 39881:6881
      - 39881:6881/udp
    restart: unless-stopped
  flaresolverr:
    image: flaresolverr/flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Asia/Shanghai
    ports:
      - 3919:8191
    restart: unless-stopped

