services:
  sonarr:
    image: linuxserver/sonarr
    ports:
      - 28681:28681
    volumes:
      - ./sonarr/config:/config
      - ./dist:/data
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    ports:
      - 26398:26398
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
    environment:
      - PUID=0
      - PGID=0
      - AUTO_UPDATE=true
      - TZ=Asia/Shanghai
    restart: unless-stopped
  qbittorrent:
    image: linuxserver/qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=22573
    volumes:
      - ./qbittorrent/config:/config
      - ./dist:/data
    ports:
      - 22573:22573
      - 39881:6881
      - 39881:6881/udp
    restart: unless-stopped
  flaresolverr:
    image: flaresolverr/flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Asia/Shanghai
    ports:
      - 3919:8191
    restart: unless-stopped

